# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: ggm_dwh
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ggm_dwh
    volumes:
      - postgres_data:/var/lib/postgresql-ggm/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d ggm_dwh"]
      interval: 30s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: ggm_dwh_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "your@email.com"
      PGADMIN_DEFAULT_PASSWORD: "yourpassword"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
  postgres_data_dev:
  pgadmin_data:
